#!/usr/bin/env bash
set -euo pipefail

doragon_report_help() {
  cat <<'USAGE'
Usage:
  doragon report [options]

Options:
  --json           Export report as JSON
  --pretty         Pretty print JSON (requires jq)
  --out <dir>      Output directory

Examples:
  doragon report
  doragon report --json
  doragon report --json --pretty
  doragon report --json --out /var/log/doragon_audit
USAGE
}

doragon_report_cmd() {
  local json=0
  local pretty=0
  local out_dir="${OUTPUT_DIR_DEFAULT}"

  if [[ $# -eq 0 ]]; then
    doragon_report_help
    return 0
  fi

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --json)
        json=1
        shift
        ;;
      --pretty)
        pretty=1
        shift
        ;;
      --out)
        [[ $# -ge 2 ]] || die "Missing value for --out"
        out_dir="$2"
        shift 2
        ;;
      --help|-h)
        doragon_report_help
        return 0
        ;;
      *)
        die "Unknown report option: $1"
        ;;
    esac
  done

  out_dir="${out_dir%/}"
  mkdir -p "${out_dir}"

  local host generated
  host="$(hostname_safe)"
  generated="$(ts)"

  local report_txt="${out_dir}/report.txt"
  local report_json="${out_dir}/report.json"

  IFS='|' read -r security_score score_status exit_code warn_count fail_count \
  < <(doragon_calculate_security_score)

  local grade assessment
  grade="$(score_grade "$security_score")"
  assessment="$(score_assessment "$security_score" "$score_status")"

  local txt_top_issues
  txt_top_issues="$(top_issues || true)"

  local txt_next_actions
  txt_next_actions="$(next_actions || true)"

 {
  section "Doragon Framework Security Report"
  echo
  info "Host: ${host}"
  info "Profile: ${DORAGON_PROFILE}"
  info "Generated: ${generated}"
  echo
  section "System"
  info "OS: $(detect_os_pretty)"
  info "Kernel: $(kernel_safe)"
  info "Uptime: $(uptime_short)"
  echo
  section "Security Core"
  info "SELinux Mode: $(getenforce_safe)"
  info "firewalld: $([[ "$(check_firewalld)" == "OK" ]] && echo "running" || echo "not running")"
  info "Fail2Ban: $([[ "$(check_fail2ban)" == "OK" ]] && echo "active ($(fail2ban_jails_count) jails)" || echo "inactive")"
  echo
  section "Network Exposure"
  info "Listeners (TCP/UDP):"
  ss -tulnp 2>/dev/null | awk '/LISTEN/ {print $0}' || true
  echo
  info "Local-only Services (Unix sockets detected):"
  info "- PHP-FPM socket: $([[ -S /run/php-fpm/www.sock ]] && echo "present" || echo "missing")"
  info "- MariaDB socket: $([[ -S /var/lib/mysql/mysql.sock ]] && echo "present" || echo "missing")"
  info "- PostgreSQL socket: $([[ -S /var/run/postgresql/.s.PGSQL.65499 ]] && echo "present" || echo "missing")"
  echo
  section "Security Score"
  info "Score: ${security_score}/100"
  info "Grade: ${grade}"
  info "Status: ${score_status}"
  info "Assessment: ${assessment}"
  echo
  section "Top Issues"
  if [[ -n "${txt_top_issues}" ]]; then
    printf '%s\n' "${txt_top_issues}" | sed 's/^/- /'
  else
    info "- No major issues detected"
  fi
  echo
  section "Next Actions"
  if [[ -n "${txt_next_actions}" ]]; then
    printf '%s\n' "${txt_next_actions}" | sed 's/^/- /'
  else
    info "- No immediate actions required"
  fi

  echo
  echo
  echo "Report generated by Doragon Framework"
  echo "STABILITY • SIMPLICITY • SECURE BY ARCHITECTURE"
  echo "https://github.com/Hitsukaya/doragon-framework"
  echo "Powered by Hitsukaya"
} > "${report_txt}"

  if [[ "${json}" -eq 1 ]]; then

  local mariadb_mode="local"
  mariadb_public_listen && mariadb_mode="public"

  local pg_mode="local"
  postgres_public_listen_65499 && pg_mode="public"

  IFS='|' read -r security_score score_status exit_code warn_count fail_count \
    < <(doragon_calculate_security_score)

  local grade assessment
  grade="$(score_grade "$security_score")"
  assessment="$(score_assessment "$security_score" "$score_status")"

  local listeners_raw_json=""
  local sep=""

  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    line=${line//\\/\\\\}
    line=${line//\"/\\\"}
    listeners_raw_json="${listeners_raw_json}${sep}\"${line}\""
    sep=", "
  done < <(ss -tulnp 2>/dev/null | awk '/LISTEN/ {print $0}')

  local top_issues_json=""
  local issues_sep=""

  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    line=${line//\\/\\\\}
    line=${line//\"/\\\"}
    top_issues_json="${top_issues_json}${issues_sep}\"${line}\""
    issues_sep=", "
  done < <(top_issues || true)

  local next_actions_json=""
  local actions_sep=""

  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    line=${line//\\/\\\\}
    line=${line//\"/\\\"}
    next_actions_json="${next_actions_json}${actions_sep}\"${line}\""
    actions_sep=", "
  done < <(next_actions || true)

  local posture_json=""
  local posture_sep=""

  posture_json="${posture_json}${posture_sep}\"Layered defense enabled.\""
  posture_sep=", "

  [[ "$(check_selinux)" == "OK" ]] && {
    posture_json="${posture_json}${posture_sep}\"SELinux enforced.\""
    posture_sep=", "
  }

  [[ "$(check_firewalld)" == "OK" ]] && {
    posture_json="${posture_json}${posture_sep}\"Firewall active.\""
    posture_sep=", "
  }

  [[ "$(check_fail2ban)" == "OK" ]] && {
    posture_json="${posture_json}${posture_sep}\"Fail2Ban multi-jail active.\""
    posture_sep=", "
  }

  [[ "$(check_redis_local_only)" == "OK" ]] && {
    posture_json="${posture_json}${posture_sep}\"Redis restricted to local-only exposure.\""
    posture_sep=", "
  }

  local recommendations_json=""
  local rec_sep=""

  mariadb_public_listen && {
    recommendations_json="${recommendations_json}${rec_sep}\"Consider restricting MariaDB to localhost-only\""
    rec_sep=", "
  }

  postgres_public_listen_65499 && {
    recommendations_json="${recommendations_json}${rec_sep}\"Consider restricting PostgreSQL to localhost-only\""
    rec_sep=", "
  }

  recommendations_json="${recommendations_json}${rec_sep}\"Consider an SSH allowlist or recovery path if using permanent bans\""

cat > "${report_json}" <<JSON
{
  "host": "${host}",
  "profile": "${DORAGON_PROFILE}",
  "generated": "${generated}",
  "status": "${score_status}",
  "exit_code": ${exit_code},
  "security_score": ${security_score},
  "grade": "${grade}",
  "assessment": "${assessment}",
  "system": {
    "os": "$(detect_os_pretty)",
    "kernel": "$(kernel_safe)",
    "uptime": {
      "days": $(uptime_days),
      "loadavg": "$(loadavg_short)",
      "rootfs": "$(rootfs_usage_line)",
      "memory": "$(mem_usage_line)",
      "swap": {
        "status": "$(swap_status)",
        "value": "$(swap_line)"
      }
    }
  },
  "security": {
    "selinux": {
      "status": "$(check_selinux)",
      "mode": "$(getenforce_safe)"
    },
    "firewalld": {
      "status": "$(check_firewalld)"
    },
    "fail2ban": {
      "status": "$(check_fail2ban)",
      "jails": $(fail2ban_jails_count)
    },
    "ssh": {
      "status_line": "$(check_sshd_port)"
    }
  },
  "services": {
    "nginx": "$(check_nginx)",
    "php_fpm": "$(check_phpfpm)",
    "php_fpm_socket": "$(check_phpfpm_socket)",
    "redis": "$(check_redis_local_only)",
    "mariadb": {
      "service_active": $(mariadb_service_active && echo "true" || echo "false"),
      "any_listen": $(mariadb_any_listen && echo "true" || echo "false"),
      "local_only": $(mariadb_local_only && echo "true" || echo "false"),
      "socket_present": $(mariadb_socket_present && echo "true" || echo "false"),
      "public_bind": $(mariadb_public_listen && echo "true" || echo "false")
    },
    "postgresql": {
      "service_active": $(postgres_service_active && echo "true" || echo "false"),
      "any_listen": $(postgres_any_listen && echo "true" || echo "false"),
      "local_only": $(postgres_local_only && echo "true" || echo "false"),
      "socket_present": $(postgres_socket_present && echo "true" || echo "false"),
      "public_bind": $(postgres_public_listen_65499 && echo "true" || echo "false")
    }
  },
  "network": {
    "open_ports_summary": "$(open_ports_summary)",
    "listeners_raw": [ ${listeners_raw_json} ]
  },
  "summary": {
    "fail_count": ${fail_count},
    "warn_count": ${warn_count}
  },
  "top_issues": [ ${top_issues_json} ],
  "next_actions": [ ${next_actions_json} ],
  "recommendations": [ ${recommendations_json} ],
  "posture": [ ${posture_json} ]
}
JSON

  if [[ "${pretty}" -eq 1 ]]; then
    if command -v jq >/dev/null 2>&1; then
      jq . "${report_json}" > "${report_json}.tmp"
      mv "${report_json}.tmp" "${report_json}"
    fi
  fi
fi

  ok "Report written: ${report_txt}"
  [[ "${json}" -eq 1 ]] && ok "JSON written: ${report_json}"
  info "Output directory: ${out_dir}"


}
